#!/bin/bash

root_dir=$(realpath $(dirname $0))

cd $root_dir/../docker/build

docker build \
    -f hugo.Dockerfile \
    -t radicalegg/hugo .

cd $root_dir/..

docker build \
    --no-cache \
    -t radicalegg/outofmana .
