#!/bin/bash

root_dir=$(realpath $(dirname $0))
[ -z $1 ] && exit 1

cd $root_dir/..
src=$(realpath "${root_dir}/../src/")

docker run \
	--rm \
	-it -v "$src:/app" \
	radicalegg/hugo:latest \
	hugo new content/posts/${1}.md

./scripts/set-perm
