#!/bin/bash

root_dir=$(realpath $(dirname $0))
[ -z $1 ] && exit 1


docker run \
	--rm \
	-it -v "/home/egg/code/blog/src/outofmana:/src" \
	klakegg/hugo:0.101.0 \
	new content/posts/${1}.md

./scripts/set-prem
